[font]
size = 11.5

[font.normal]
family = 'InputMonoNarrow Nerd Font'
style = 'Light'

[font.bold]
family = 'InputMonoNarrow Nerd Font'
style = 'Light'

[font.italic]
family = 'InputMonoNarrow Nerd Font'
style = 'Light'

[font.bold_italic]
family = 'InputMonoNarrow Nerd Font'
style = 'Light'

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0
