[font]
size = 11

[font.normal]
family = 'TX-02'
style = 'Medium'

[font.bold]
family = 'TX-02'
style = 'Medium'

[font.italic]
family = 'TX-02'
style = 'Medium'

[font.bold_italic]
family = 'TX-02'
style = 'Medium'

[font.offset]
x = 1
y = 5

[font.glyph_offset]
x = 0
y = 2
