#!/bin/fish

set paths                  \
  .psqlrc                  \
  .zshrc                   \
  .gitconfig               \
  .rndebuggerrc            \
  .config/nvim             \
  .config/kitty            \
  .config/pgcli            \
  .config/qtile            \
  .config/fish/config.fish \
  .config/zk               \

set dotfiles ~/dotfiles

for path in $paths
  set fullpath ~/$path
  set item (basename $path)

  if test ! -e $dotfiles/$item
    cp -r $fullpath $dotfiles 
  end

  if test -e $dotfiles/$item
    rm -rf $fullpath
  end

  if test ! -e $fullpath
    mkdir -p (dirname $fullpath)
    ln -s $dotfiles/$item $fullpath
  end
end


