#!/bin/fish

set paths       \
  .psqlrc       \
  .zshrc        \
  .gitconfig    \
  .config/nvim  \
  .config/kitty \
  .config/pgcli \
  .config/qtile \
  .config/fish  \

set dotfiles ~/dotfiles

for path in $paths
  set fullpath ~/$path
  set item (basename $path)

  if test ! -e $dotfiles/$item
    cp -r $fullpath $dotfiles 
  end

  if test -e $dotfiles/$item
    rm $fullpath
  end

  if test ! -e $fullpath
    ln -s $dotfiles/$item $fullpath
  end
end


