font_size          10.5
font_family        family="Eirian" style="Regular"
bold_font          family="Eirian" style="Regular"
italic_font        family="Eirian" style="Regular"
bold_italic_font   family="Eirian" style="Regular"
modify_font        baseline 0
modify_font        cell_width 100%
adjust_line_height 120%
#text_composition_strategy 1.0 0
