font_size          8
font_family        family="JetBrains Mono" style="Regular"
bold_font          family="JetBrains Mono" style="Regular"
italic_font        family="JetBrains Mono" style="Regular"
bold_italic_font   family="JetBrains Mono" style="Regular"
modify_font        baseline 0
modify_font        cell_width 100%
adjust_line_height 100%
#text_composition_strategy 1.0 0
