#! /bin/bash

## STARTUP ##

killall pulseaudio &
picom -b &
nitrogen --set-scaled ~/Pictures/Wallpapers/wallhaven-4opomm_3840x2160.png
mpris-proxy & 
# $HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap -option ctrl:swapcaps &
xsetroot -cursor_name left_ptr & 
pulseaudio &
xset r rate 220 50 & # type speed
xinput --set-prop 14 179 0.3 0 0 0 0.3 0 0 0 1 # mouse speed

# previous_count=0 
# bspc subscribe node_focus | while IFS=' ' read -r _ _ did _ wid _; do
#   count=`bspc query -N -d $somedesktop -n .window.\!hidden | wc -l`

#   if [[ $count == $previous_count ]]; then
#     exit
#   fi

#   if [[ $count == 1 ]]; then
#     bspc config border_width 0;
#     bspc config -n focused border_width 0;
#   else
#     bspc config border_width 3;
#     bspc config -n focused border_width 3;
#   fi

#   previous_count=$count
# done

bspc monitor -d 1 2 3 4 5 6 7 8 

## WINDOW CONFIGUARTION ##

bspc config window_gap            8 
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding           2

## BSPWM COLORING ##

bspc config border_width 0
bspc config -n focused border_width 0
bspc config normal_border_color   "#4C566A"
bspc config active_border_color   "#a3b8ef"
bspc config focused_border_color  "#a3b8ef"
bspc config presel_feedback_color "#a3b8ef"
bspc config urgent_border_color   "#a3b8ef"

## APPLICATION RULES ##

# can use xprop
bspc rule -a Brave-browser desktop=2
bspc rule -a TelegramDesktop desktop=3
bspc rule -a Slack desktop=3
bspc rule -a DBeaver desktop=4
bspc rule -a Pomodoro desktop=4
bspc rule -a Zathura state=tiled
