#! /bin/bash

## SXHKD CONFIG ##
super + space
  {setxkbmap ru, setxkbmap us}

Print
  scrot -s -q 100 -f -e 'xclip -selection clipboard -t image/png -i $f; mkdir ~/screenshots; mv $f -f -t ~/screenshots/'

shift + Print
  scrot -u -s -q 100 -f -e 'xclip -selection clipboard -t image/png -i $f; mkdir ~/screenshots; mv $f -f -t ~/screenshots/'

super + Return
	alacritty

super + e
	thunar

super + shift + b
	brave

super + shift + d
	dbeaver-ce

super + shift + s
	slack

super + shift + t
  steam

super + shift + m
	telegram-desktop

super + shift + z
	~/dotfiles/scripts/open_books.sh

super + e
	nautilus

super + d
	rofi -show drun

super + Escape
	pkill -USR1 -x sxhkd

super + ctrl + r
	bspc wm -r

super + shift + c
	bspc node -c

# super + z
#   bspc node -t \~fullscreen

super + shift + ctrl + r
  reboot

super + shift + ctrl + q
  poweroff

super + ctrl + s
  systemctl suspend

super + Tab
	bspc node -f last

super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

super + {1-9,0}
	bspc desktop -f ^{1-9,10}

super + shift + {1-9,0}
  bspc node -d ^{1-9,10} --follow

# alternate between the tiled and monocle layout
super + z
	bspc desktop -l next

super + f
  bspc node -t ~floating

super + {t,shift + t,shift + @space}
	bspc node -t {tiled,pseudo_tiled,floating}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

super + grave
  bspc desktop -l monocle; \
  bspc node -f next.local.window -a

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

super + ctrl + {1-9}
	bspc node -o 0.{1-9}

super + s
  bspc node -n 'last.!automatic.local'

# AUDIO
XF86AudioRaiseVolume
  pactl set-sink-volume @DEFAULT_SINK@ +5%
	#wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%+
XF86AudioLowerVolume
  pactl set-sink-volume @DEFAULT_SINK@ -5%
	#wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-
XF86AudioMute
  pactl set-sink-mute @DEFAULT_SINK@ toggle
  #wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

