gui:
  sidePanelWidth: 0.2
  commitLength:
    show: false
  showListFooter: false
  showRandomTip: false
  showBottomLine: false
  showCommandLog: false
  showPanelJumps: false
  border: 'rounded'
  # border: 'hidden'
  filterMode: 'fuzzy'
  # mainPanelSplitMode: 'flexible'

git:
  diffRenderers:
    - command: delta --light --paging=never --line-numbers --hyperlinks --hunk-header-style="syntax bold box" --hunk-header-decoration-style="blue box"
    - command: diff-so-fancy
    - type: rawGit # git's default diff

promptToReturnFromSubprocess: false

os:
  # editPreset: nvim
  edit: "nu ~/dotfiles/scripts/open-lazygit-in-neovim.nu {{filename}}"
  editAtLine: "nu ~/dotfiles/scripts/open-lazygit-in-neovim.nu {{filename}} {{line}}"
  editAtLineAndWait: ""
  editInTerminal: true
  # open isn't working for nvim, idk why, so just to use edit command in any case
  # open: nu ~/dotfiles/scripts/open-lazygit-in-neovim.nu {{filename}}

customCommands:
  - key: 'D'
    # command: 'fish -c "git diff origin/master...{{.SelectedLocalBranch.Name}} | difft"'
    command: "git difftool -y {{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}}"
    # context: 'localBranches'
    context: 'commitFiles'
    description: 'Diff with master'
    # subprocess: true
