gui:
  nerdFontsVersion: "3"
  sidePanelWidth: 0.25
  commitLength:
    show: false
  showListFooter: false
  showRandomTip: false
  showBottomLine: false
  showCommandLog: false
  showPanelJumps: false
  # border: 'rounded'
  border: 'hidden'
  filterMode: 'fuzzy'

git:
  paging:
    colorArg: always
    pager: diff-so-fancy
    # externalDiffCommand: difft --color=always --display=side-by-side-show-both --syntax-highlight=on
    # pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

promptToReturnFromSubprocess: false

os:
  editPreset: nvim
  edit: nu ~/dotfiles/scripts/open-lazygit-in-neovim.nu {{filename}}
  editAtLine: nu ~/dotfiles/scripts/open-lazygit-in-neovim.nu {{filename}} {{line}}
  # open isn't working for nvim, idk why, so just to use edit command in any case
  # open: nu ~/dotfiles/scripts/open-lazygit-in-neovim.nu {{filename}}

customCommands:
  - key: 'D'
    # command: 'fish -c "git diff origin/master...{{.SelectedLocalBranch.Name}} | difft"'
    command: "git difftool -y {{.SelectedLocalCommit.Sha}} -- {{.SelectedCommitFile.Name}}"
    # context: 'localBranches'
    context: 'commitFiles'
    description: 'Diff with master'
    # subprocess: true
