vim.g.base46_cache = vim.fn.stdpath('data') .. '/base46_cache/'

require 'constants'
require 'helpers.global'
require 'options'
require 'autocommands'
require 'commands'
require 'maps'
require 'plugins'
require 'neovide'
