--  rosewater = "#f2d5cf",
-- 	flamingo = "#eebebe",
-- 	pink = "#f4b8e4",
-- 	mauve = "#ca9ee6",
-- 	red = "#e78284",
-- 	maroon = "#ea999c",
-- 	peach = "#ef9f76",
-- 	yellow = "#e5c890",
-- 	green = "#a6d189",
-- 	teal = "#81c8be",
-- 	sky = "#99d1db",
-- 	sapphire = "#85c1dc",
-- 	blue = "#8caaee",
-- 	lavender = "#babbf1",
-- 	text = "#c6d0f5",
-- 	subtext1 = "#b5bfe2",
-- 	subtext0 = "#a5adce",
-- 	overlay2 = "#949cbb",
-- 	overlay1 = "#838ba7",
-- 	overlay0 = "#737994",
-- 	surface2 = "#626880",
-- 	surface1 = "#51576d",
-- 	surface0 = "#414559",
-- 	base = "#303446",
-- 	mantle = "#292c3c",
-- 	crust = "#232634",

return {
	'catppuccin/nvim',
	name = 'catppuccin',
	priority = 1000,
	config = function()
		require('catppuccin').setup {
            term_colors = true,
			flavour = 'frappe', -- latte, frappe, macchiato, mocha
			transparent_background = true,
			styles = { -- Handles the styles of general hi groups (see `:h highlight-args`):
				comments = { 'italic' }, -- Change the style of comments
				conditionals = { 'italic' },
				loops = { 'italic' },
				functions = {},
				keywords = { 'italic' },
				strings = {},
				variables = {},
				numbers = {},
				booleans = {},
				properties = {},
				types = {},
				operators = {},
			},
			color_overrides = {
				all = {
					-- green = '#81c8be',
					-- red = '#eb6f92',
					-- blue = '#a3b8ef',

					-- mauve = '#ADD7FF',
					-- yellow = '#A6ACCD',
					-- maroon = '#9398cf',
					-- peach = '#ebbcba',
					-- overlay2 = '#89DDFF'
				},
			},
			custom_highlights = function(colors)
				return {
					['@text'] = { fg = colors.surface0 },
					-- ['@punctuation.bracket'] = { italic = true },
					MiniCursorword = { underline = false, link = 'Visual' },
					MiniCursorwordCurrent = { link = 'MiniCursorword' },
					NormalFloat = { bg = 'NONE' },
					FloatBorder = { fg = colors.surface0, bg = 'NONE' },
					FzfLuaNormal = { link = 'NormalFloat' },
					FzfLuaBorder = { link = 'FloatBorder' },
					NoiceCmdlinePopupBorder = { link = 'FloatBorder' },
					IndentBlanklineChar = { fg = colors.surface0 },
					FzfLuaTitle = { bg = colors.green, fg = colors.base, bold = false },
					FzfLuaHeaderText = { fg = colors.sky },
					TreeSitterContext = { underline = false, bg = colors.surface0 },
					TreeSitterContextBottom = { underline = false, bg = colors.surface0 },

                    ["@lsp.typemod.selfKeyword"] = { fg = colors.red },
                    ["@lsp.type.selfTypeKeyword"] = { fg = colors.red },
                    ["@lsp.typemod.decorator"] = { link = "special" },
                    ["@namespace"] = { style = { "nocombine" } },
                    ["@module"] = { style = { "nocombine" } },
                    TreesitterContextLineNumber = { fg = "#494D64", bg = "#1e2030" },
                    CursorLine = { bg = "#292D3F" },
                    Comment = { link = "NvimTreeFolderIcon" },
                    WinbarFolder = { fg = "#8F98B8" },
                    WinbarFileName = { fg = "#B6BDFD" },
                    ["@function.builtin"] = { link = "Function" },
                    ["@punctuation.bracket"] = { link = "Comment", italic = true },
                    ["@punctuation.special.rust"] = { link = "Comment" },
                    String = { fg = "#92be83" },
                    GlancePreviewMatch = { fg = "#ffffff", bg = "#304E75" },
                    GlanceWinbarFileName = { link = "NvimTreeRootFolder" },
                    GlanceListMatch = { fg = "#8AADF4" },
                    CmpItemAbbrMatch = { fg = "none", style = { "bold" } },
                    CmpItemAbbrMatchFuzzy = { link = "CmpItemAbbrMatch" },
                    GlanceWinbarFolderName = { link = "Comment" },
                    GlanceListCursorLine = { bg = "#212635" },
                    -- GlanceListNormal = { fg = "#8F98B8", bg = "#15182A" },
                    -- GlancePreviewNormal = { bg = "#1A1E30" },
                    LspInlayHint = { fg = "#8D98BB", bg = colors.none },
                    NvimTreeOpenedFile = { fg = "#cad3f5" },
                    NvimTreeRootFolder = { fg = "#B6BDFD", style = { "nocombine" } },
                    NvimTreeFolderName = { link = "Directory" },
                    NvimTreeOpenedFolderName = { link = "NvimTreeOpenedFile" },
                    NvimTreeFolderIcon = { link = "Directory" },
                    NvimTreeFileIcon = { fg = "#CAD3F5" },
                    NvimTreeCursorLine = { bg = "#24273A" },
                    NvimTreeNormal = { bg = "#1e2030", fg = "#8F98B8" },
                    Folded = { link = "CursorLine" },
                    Directory = { fg = "#8F98B8" },
                    ArrowCurrentFile = { link = "Comment" },
                    TermCursor = { fg = "#000000", bg = "#B7BDF8" },
                    Visual = { bg = "#304E75", style = { "nocombine" } },
                    NvimTreeWinSeparator = { link = "WinSeparator" },
                    CmpGhostText = { fg = "#6C7086", style = { "italic" } },
                    CmpItemMenu = { link = "Comment" },
                    TelescopeMatching = { style = { "bold" } },
                    TelescopeNormal = { bg = "#1E2031", style = { "nocombine" } },
                    TelescopeBorder = { bg = "#1E2031", style = { "nocombine" } },
                    TelescopeSelection = { style = { "nocombine" } },
                    MyNormalFloat = { bg = "#1e2030" },
                    MyCursorLine = { bg = "#283E5B" },
                    MatchParen = { fg = "#F0C6C6", style = { "nocombine" }, bg = colors.none },
                    LualineCursorLine = { bg = "#2A2B3C" },
                    Unvisited = { bg = "#34344F" },
                    MiniIndentscopeSymbol = { fg = "#6C7086" },
                    illuminatedwordwrite = { bg = "#253C59" },
                    illuminatedwordread = { bg = "#32354A" },
                    illuminatedWordText = { bg = "#32354A" },
				}
			end,
			integrations = {
				cmp = true,
				gitsigns = true,
				nvimtree = true,
				treesitter = true,
				notify = false,
				noice = true,
				treesitter_context = true,
				hop = true,
				mini = {
					enabled = true,
					indentscope_color = '',
				},
				native_lsp = {
					enabled = true,
					virtual_text = {
						errors = { 'italic' },
						hints = { 'italic' },
						warnings = { 'italic' },
						information = { 'italic' },
					},
					underlines = {
						errors = { 'undercurl' },
						hints = { 'undercurl' },
						warnings = { 'undercurl' },
						information = { 'undercurl' },
					},
				},
			},
		}

		vim.cmd.colorscheme 'catppuccin'
	end,
}
