#!/usr/bin/env bash

#   Run 
#   `ln -sf ~/dotfiles/scripts/nu-run ~/.local/bin/nu-run`
#   to add into bin

config_dir="$HOME/dotfiles/nushell"

exec nu --config "$config_dir/config.nu" --env-config "$config_dir/env.nu" "$@"
